// <auto-generated />
using System;
using ContactsAndCallsAccountingSystem.DAL;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ContactsAndCallsAccountingSystem.DAL.Migrations
{
    [DbContext(typeof(ContactsAndCallsAccountingSystemContext))]
    [Migration("20220619162155_Init")]
    partial class Init
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("ContactsAndCallsAccountingSystem.DAL.Entities.Call", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Calltype")
                        .HasColumnType("int");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Calls");
                });

            modelBuilder.Entity("ContactsAndCallsAccountingSystem.DAL.Entities.CallProfile", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("Billing")
                        .HasColumnType("decimal(18,2)");

                    b.Property<Guid>("CallId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("PhoneProfile")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("CallId");

                    b.HasIndex("PhoneProfile");

                    b.ToTable("CallProfile");
                });

            modelBuilder.Entity("ContactsAndCallsAccountingSystem.DAL.Entities.Profile", b =>
                {
                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Patronymic")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("PhoneNumber");

                    b.ToTable("Profiles");
                });

            modelBuilder.Entity("ContactsAndCallsAccountingSystem.DAL.Entities.CallProfile", b =>
                {
                    b.HasOne("ContactsAndCallsAccountingSystem.DAL.Entities.Call", "Call")
                        .WithMany("CallProfile")
                        .HasForeignKey("CallId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ContactsAndCallsAccountingSystem.DAL.Entities.Profile", "Profile")
                        .WithMany("CallProfile")
                        .HasForeignKey("PhoneProfile")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Call");

                    b.Navigation("Profile");
                });

            modelBuilder.Entity("ContactsAndCallsAccountingSystem.DAL.Entities.Call", b =>
                {
                    b.Navigation("CallProfile");
                });

            modelBuilder.Entity("ContactsAndCallsAccountingSystem.DAL.Entities.Profile", b =>
                {
                    b.Navigation("CallProfile");
                });
#pragma warning restore 612, 618
        }
    }
}
